matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc-6
script:
  - make
  - pip install --user cpp-coveralls
after_success:
  - if [ "$CXX" == "g++" ]; then
        coveralls --exclude tests --gcov-options '\-lp \--relative-only';
    fi;