matrix:
  include:
    - os: linux
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['valgrind']
dist: trusty
sudo: required
language:
  - cpp
script:
  - make test_all
  # - valgrind --leak-check=full ./test_csv_parser
  # Disable until Travis updates their version of Valgrind
after_success:
  - cd test_results;
  - bash <(curl -s https://codecov.io/bash);