matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
dist: trusty
sudo: required
language:
  - cpp
before_script:
  - pip3 install pexpect
script:
  - export CC=gcc-6
  - export CXX=g++-6
  - make test_all
  - pip3 install --user cpp-coveralls
after_success:
  - if [ "$CXX" == "g++-6" ]; then
        coveralls --exclude tests --gcov-options '\-lp \--relative-only';
    fi;
