os: linux
dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
  - clang
script:
  - make
  - pip install --user cpp-coveralls
after_success:
  - coveralls --exclude src --exclude tests --gcov-options '\-lp'